
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHILEEND = 13;
  public static final int FUNCTION = 26;
  public static final int READLINE = 18;
  public static final int CHAR = 37;
  public static final int ENDSUB = 20;
  public static final int PERIOD = 3;
  public static final int INTEGER = 36;
  public static final int PRIVATE = 23;
  public static final int FOR = 14;
  public static final int WHITESPACE = 31;
  public static final int STATIC = 22;
  public static final int NOT = 4;
  public static final int AND = 5;
  public static final int ELSEIF = 10;
  public static final int ENDFUNCTION = 21;
  public static final int TYPE = 35;
  public static final int OR = 6;
  public static final int NEXT = 16;
  public static final int IF = 7;
  public static final int ADDITIONOPERATOR = 40;
  public static final int ID = 34;
  public static final int CLOSEPARENTHESIS = 30;
  public static final int DIM = 27;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MULTIPLICATIONOPERATOR = 39;
  public static final int MOD = 17;
  public static final int OPENPARENTHESIS = 29;
  public static final int ENDIF = 11;
  public static final int ELSE = 9;
  public static final int TO = 15;
  public static final int WHILE = 12;
  public static final int PUBLIC = 24;
  public static final int THEN = 8;
  public static final int ENDOFLINE = 32;
  public static final int STRING = 33;
  public static final int RELATIONALOPERATOR = 38;
  public static final int AS = 28;
  public static final int SUB = 25;
  public static final int PRINT = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PERIOD",
  "NOT",
  "AND",
  "OR",
  "IF",
  "THEN",
  "ELSE",
  "ELSEIF",
  "ENDIF",
  "WHILE",
  "WHILEEND",
  "FOR",
  "TO",
  "NEXT",
  "MOD",
  "READLINE",
  "PRINT",
  "ENDSUB",
  "ENDFUNCTION",
  "STATIC",
  "PRIVATE",
  "PUBLIC",
  "SUB",
  "FUNCTION",
  "DIM",
  "AS",
  "OPENPARENTHESIS",
  "CLOSEPARENTHESIS",
  "WHITESPACE",
  "ENDOFLINE",
  "STRING",
  "ID",
  "TYPE",
  "INTEGER",
  "CHAR",
  "RELATIONALOPERATOR",
  "MULTIPLICATIONOPERATOR",
  "ADDITIONOPERATOR"
  };
}

